apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: rstudio-7486-mapping
      add_request_headers:
        X-Forwarded-Proto: https

      prefix: /private/rstudio/renci/7486/
      rewrite: /private/rstudio/renci/7486/
      service: rstudio-7486:8080

      headers:
          REMOTE_USER: murali_karthik


      bypass_auth: true
      timeout_ms: 300000
      idle_timeout_ms: 500000
      connect_timeout_ms: 500000
      use_websocket: true
  labels:
    app: rstudio-7486
  name: rstudio-7486
spec:
  ports:
  - name: rstudio-7486
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rstudio-7486
  type: ClusterIP
